export const LOGIN = "LOGIN"
export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const ADD_USER = "ADD_USER"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_USER"
export const DELETE_USERS = "DELETE_USERS"
export const CHANGE_STATUS = "CHANGE_STATUS"
export const FETCH_USERS = "FETCH_USERS"
